import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';

// Supported languages
export type Language = 'uk' | 'en' | 'ru';

// Context type
type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

// Create context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations object
const translations: Record<Language, Record<string, string>> = {
  uk: {
    // Ukrainian translations
    'home': 'Головна',
    'about': 'Про лікаря',
    'services': 'Послуги',
    'conditions': 'Захворювання',
    'contact': 'Контакти',
    'doctor_name': 'Др. Іванов Іван Іванович',
    'doctor_specialty': 'Уролог-Андролог',
    'hero_title': 'Професійна урологічна допомога',
    'hero_subtitle': 'Спеціалізована діагностика та лікування урологічних і андрологічних захворювань',
    'cta_button': 'Записатися на прийом',
    'about_title': 'Про мене',
    'experience': 'років досвіду',
    'patients': 'задоволених пацієнтів',
    'services_title': 'Мої послуги',
    'conditions_title': 'Основні захворювання',
    'contact_title': 'Зв\'яжіться зі мною',
    'phone': 'Телефон',
    'email': 'Електронна пошта',
    'address': 'Адреса',
    'consultation_hours': 'Години консультацій',
    'monday_friday': 'Понеділок - П\'ятниця',
    'saturday': 'Субота',
    'sunday': 'Неділя',
    'closed': 'Зачинено',
    'message': 'Повідомлення',
    'your_name': 'Ваше ім\'я',
    'your_email': 'Ваша електронна пошта',
    'your_message': 'Ваше повідомлення',
    'send_message': 'Надіслати повідомлення',
    'copyright': 'Всі права захищені',
    'choose_language': 'Оберіть мову',
    'footer_description': 'Спеціалізована медична допомога у сфері урології та андрології. Професійна діагностика та лікування.',
    'quick_links': 'Швидкі посилання',
    'contact_info': 'Контактна інформація',
    'published_research': 'Наукових публікацій',
    'urological_diagnostics': 'Урологічна діагностика',
    'urological_diagnostics_desc': 'Комплексна оцінка та діагностика урологічних захворювань за допомогою сучасного обладнання.',
    'andrological_treatment': 'Андрологічне лікування',
    'andrological_treatment_desc': 'Спеціалізоване лікування проблем чоловічого репродуктивного здоров\'я та сексуальної дисфункції.',
    'preventative_care': 'Профілактична допомога',
    'preventative_care_desc': 'Проактивні стратегії охорони здоров\'я для запобігання урологічним та андрологічним проблемам.',
    'condition_bph': 'Доброякісна гіперплазія простати (ДГПЗ)',
    'condition_ed': 'Еректильна дисфункція',
    'condition_uti': 'Інфекції сечовивідних шляхів',
    'condition_stones': 'Камені в нирках',
    'condition_prostatitis': 'Простатит',
    'condition_infertility': 'Чоловіче безпліддя',
    'condition_testicular': 'Захворювання яєчок',
    'condition_bladder': 'Рак сечового міхура',
    'ready_schedule': 'Готові записатися на прийом?',
    'highest_quality': 'Наша команда готова надати вам урологічну та андрологічну допомогу найвищої якості.',
    'call_now': 'Зателефонувати',
    'view_all_services': 'Переглянути всі послуги',
    'view_all_conditions': 'Переглянути всі захворювання',
    'info_description': 'Спеціалізована діагностика та лікування широкого спектру урологічних та андрологічних захворювань.',
    'page_not_found': 'Сторінку не знайдено',
    'page_not_found_desc': 'Сторінка, яку ви шукаєте, можливо, була видалена, перейменована або тимчасово недоступна.',
    'return_home': 'Повернутися на головну',
    'go_back': 'Повернутися назад',
    'doctor_description': 'Більше 15 років професійного досвіду. Допомагаю чоловікам вирішувати питання здоров\'я сучасними та ефективними методами, приділяючи увагу кожному пацієнту та його індивідуальним потребам. Моя мета — не лише усунути симптоми, але й відновити якість життя, підтримати вас на кожному етапі лікування. Консультація — перший крок до вашого здоров\'я та впевненості. Запишіться прямо зараз, щоб отримати кваліфіковану допомогу, турботу та персональний підхід!',
    'all_rights_reserved': 'Всі права захищені',
    'about_subtitle': 'Узнайте больше о моем опыте, квалификации и подходе к урологической и андрологической помощи',
    'doctor_description_1': 'Маючи більше 15 років досвіду в урології та андрології, я присвятив свою кар\'єру наданню виняткової допомоги пацієнтам з урологічними проблемами та проблемами репродуктивного здоров\'я.',
    'doctor_description_2': 'Мій підхід поєднує найновіші методи лікування, засновані на доказовій медицині, з співчутливою, орієнтованою на пацієнта філософією. Я вірю в лікування всього людини, а не лише захворювання.',
    'doctor_description_3': 'Протягом усієї моєї кар\'єри я залишаюсь відданим постійному навчанню та перебуванню на передньому краї досягнень в урологічній медицині, щоб надати моїм пацієнтам найкращу можливу допомогу.',
    'compassionate_care': 'Турботливий підхід',
    'award_winning': 'Визнаний спеціаліст',
    'education': 'Образование',
    'certifications': 'Сертифікати',
    'patient_reviews': 'відгуків пацієнтів',
    'doctor_of_medicine': 'Доктор медицини',
    'residency_in_urology': 'Ординатура з урології',
    'fellowship_in_andrology': 'Стажування з андрології',
    'kyiv_medical_university': 'Київський медичний університет',
    'national_medical_academy': 'Національна медична академія післядипломної освіти',
    'european_association': 'Європейська асоціація урології',
    'urologist': 'Уролог',
    'senior_urologist': 'Старший уролог',
    'head_of_urology': 'Завідувач урологічного відділення',
    'kyiv_city_clinical_hospital': 'Київська міська клінічна лікарня',
    'medical_center_health': 'Медичний центр "Здоровʼя"',
    'medcare_clinic': 'Клініка "МедКеа"',
    'european_board': 'Сертифікація Європейської ради урології',
    'advanced_training': 'Просунута підготовка з чоловічого репродуктивного здоров\'я',
    'laser_surgery': 'Сертифікація з лазерної хірургії в урології',
    'minimally_invasive': 'Мінімально інвазивні хірургічні техніки',
    'my_approach': 'Мій підхід',
    'patient_centered': 'Орієнтованість на пацієнта',
    'patient_centered_desc': 'Я вважаю важливим ставитися до кожного пацієнта як до особистості, приділяючи час розумінню їх конкретних проблем та розробці індивідуальних планів лікування.',
    'evidence_based': 'Доказова медицина',
    'evidence_based_desc': 'Мої методи лікування засновані на останніх наукових дослідженнях та клінічних рекомендаціях для забезпечення найвищого стандарту медичної допомоги.',
    'continuous_education': 'Безперервна освіта',
    'continuous_education_desc': 'Я регулярно беру участь у медичних конференціях та семінарах, щоб бути в курсі останніх досягнень у урології та андрології.'
  },
  en: {
    // English translations
    'home': 'Home',
    'about': 'About',
    'services': 'Services',
    'conditions': 'Conditions',
    'contact': 'Contact',
    'doctor_name': 'Dr. John Smith',
    'doctor_specialty': 'Urologist-Andrologist',
    'hero_title': 'Professional Urological Care',
    'hero_subtitle': 'Specialized diagnosis and treatment of urological and andrological diseases',
    'cta_button': 'Book an Appointment',
    'about_title': 'About Me',
    'experience': 'years of experience',
    'patients': 'satisfied patients',
    'services_title': 'My Services',
    'conditions_title': 'Common Conditions',
    'contact_title': 'Get in Touch',
    'phone': 'Phone',
    'email': 'Email',
    'address': 'Address',
    'consultation_hours': 'Consultation Hours',
    'monday_friday': 'Monday - Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'closed': 'Closed',
    'message': 'Message',
    'your_name': 'Your Name',
    'your_email': 'Your Email',
    'your_message': 'Your Message',
    'send_message': 'Send Message',
    'copyright': 'All rights reserved',
    'choose_language': 'Choose Language',
    'footer_description': 'Specialized medical care in the field of urology and andrology. Professional diagnosis and treatment.',
    'quick_links': 'Quick Links',
    'contact_info': 'Contact Info',
    'published_research': 'Published Research',
    'urological_diagnostics': 'Urological Diagnostics',
    'urological_diagnostics_desc': 'Comprehensive assessment and diagnosis of urological conditions using state-of-the-art equipment.',
    'andrological_treatment': 'Andrological Treatment',
    'andrological_treatment_desc': 'Specialized treatment for male reproductive health issues and sexual dysfunction.',
    'preventative_care': 'Preventative Care',
    'preventative_care_desc': 'Proactive healthcare strategies to prevent urological and andrological issues.',
    'condition_bph': 'Benign Prostatic Hyperplasia (BPH)',
    'condition_ed': 'Erectile Dysfunction',
    'condition_uti': 'Urinary Tract Infections',
    'condition_stones': 'Kidney Stones',
    'condition_prostatitis': 'Prostatitis',
    'condition_infertility': 'Male Infertility',
    'condition_testicular': 'Testicular Disorders',
    'condition_bladder': 'Bladder Cancer',
    'ready_schedule': 'Ready to Schedule Your Appointment?',
    'highest_quality': 'Our team is ready to provide you with the highest quality urological and andrological care.',
    'call_now': 'Call Now',
    'view_all_services': 'View all services',
    'view_all_conditions': 'View all conditions',
    'info_description': 'Specialized in the diagnosis and treatment of a wide range of urological and andrological conditions.',
    'page_not_found': 'Page Not Found',
    'page_not_found_desc': 'The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.',
    'return_home': 'Return Home',
    'go_back': 'Go Back',
    'doctor_description': 'Over 15 years of professional experience. I help men address health issues using modern and effective methods, paying attention to each patient and their individual needs. My goal is not only to eliminate symptoms but also to restore quality of life, supporting you at every stage of treatment. A consultation is the first step towards your health and confidence. Book now to receive qualified care, attention, and a personalized approach!',
    'all_rights_reserved': 'All rights reserved',
    'european_board': 'European Board of Urology Certification',
    'advanced_training': 'Advanced Training in Male Reproductive Health',
    'laser_surgery': 'Laser Surgery in Urology Certification',
    'minimally_invasive': 'Minimally Invasive Surgical Techniques',
    'my_approach': 'My Approach',
    'patient_centered': 'Patient-Centered Care',
    'patient_centered_desc': 'I believe in treating each patient as an individual, taking the time to understand their specific concerns and developing personalized treatment plans.',
    'evidence_based': 'Evidence-Based Medicine',
    'evidence_based_desc': 'My treatments are based on the latest scientific research and clinical guidelines to ensure the highest standard of care.',
    'continuous_education': 'Continuous Education',
    'continuous_education_desc': 'I regularly participate in medical conferences and workshops to stay updated with the latest advancements in urology and andrology.',
    'doctor_of_medicine': 'Doctor of Medicine',
    'kyiv_medical_university': 'Kyiv Medical University',
    'residency_in_urology': 'Residency in Urology',
    'national_medical_academy': 'National Medical Academy of Postgraduate Education',
    'fellowship_in_andrology': 'Fellowship in Andrology',
    'european_association': 'European Association of Urology',
    'urologist': 'Urologist',
    'senior_urologist': 'Senior Urologist',
    'head_of_urology': 'Head of Urology Department',
    'kyiv_city_clinical_hospital': 'Kyiv City Clinical Hospital',
    'medical_center_health': 'Medical Center "Health"',
    'medcare_clinic': 'MedCare Clinic',
  },
  ru: {
    // Russian translations
    'home': 'Главная',
    'about': 'О враче',
    'services': 'Услуги',
    'conditions': 'Заболевания',
    'contact': 'Контакты',
    'doctor_name': 'Др. Иванов Иван Иванович',
    'doctor_specialty': 'Уролог-Андролог',
    'hero_title': 'Профессиональная урологическая помощь',
    'hero_subtitle': 'Специализированная диагностика и лечение урологических и андрологических заболеваний',
    'cta_button': 'Записаться на прием',
    'about_title': 'Обо мне',
    'experience': 'лет опыта',
    'patients': 'довольных пациентов',
    'services_title': 'Мои услуги',
    'conditions_title': 'Основные заболевания',
    'contact_title': 'Свяжитесь со мной',
    'phone': 'Телефон',
    'email': 'Электронная почта',
    'address': 'Адрес',
    'consultation_hours': 'Часы консультаций',
    'monday_friday': 'Понедельник - Пятница',
    'saturday': 'Суббота',
    'sunday': 'Воскресенье',
    'closed': 'Закрыто',
    'message': 'Сообщение',
    'your_name': 'Ваше имя',
    'your_email': 'Ваша электронная почта',
    'your_message': 'Ваше сообщение',
    'send_message': 'Отправить сообщение',
    'copyright': 'Все права защищены',
    'choose_language': 'Выберите язык',
    'footer_description': 'Специализированная медицинская помощь в области урологии и андрологии. Профессиональная диагностика и лечение.',
    'quick_links': 'Быстрые ссылки',
    'contact_info': 'Контактная информация',
    'published_research': 'Научных публикаций',
    'urological_diagnostics': 'Урологическая диагностика',
    'urological_diagnostics_desc': 'Комплексная оценка и диагностика урологических заболеваний с помощью современного оборудования.',
    'andrological_treatment': 'Андрологическое лечение',
    'andrological_treatment_desc': 'Специализированное лечение проблем мужского репродуктивного здоровья и сексуальной дисфункции.',
    'preventative_care': 'Профилактическая помощь',
    'preventative_care_desc': 'Проактивные стратегии здравоохранения для предотвращения урологических и андрологических проблем.',
    'condition_bph': 'Доброкачественная гиперплазия простаты (ДГПЖ)',
    'condition_ed': 'Эректильная дисфункция',
    'condition_uti': 'Инфекции мочевыводящих путей',
    'condition_stones': 'Камни в почках',
    'condition_prostatitis': 'Простатит',
    'condition_infertility': 'Мужское бесплодие',
    'condition_testicular': 'Заболевания яичек',
    'condition_bladder': 'Рак мочевого пузыря',
    'ready_schedule': 'Готовы записаться на прием?',
    'highest_quality': 'Наша команда готова предоставить вам урологическую и андрологическую помощь высочайшего качества.',
    'call_now': 'Позвонить',
    'view_all_services': 'Просмотреть все услуги',
    'view_all_conditions': 'Просмотреть все заболевания',
    'info_description': 'Специализация в диагностике и лечении широкого спектра урологических и андрологических заболеваний.',
    'page_not_found': 'Страница не найдена',
    'page_not_found_desc': 'Страница, которую вы ищете, возможно, была удалена, переименована или временно недоступна.',
    'return_home': 'Вернуться на главную',
    'go_back': 'Вернуться назад',
    'doctor_description': 'Более 15 лет профессионального опыта. Помогаю мужчинам решать вопросы здоровья современными и эффективными методами, уделяя внимание каждому пациенту и его индивидуальным потребностям. Моя цель — не только устранить симптомы, но и восстановить качество жизни, поддержать вас на каждом этапе лечения. Консультация — первый шаг к вашему здоровью и уверенности. Запишитесь прямо сейчас, чтобы получить квалифицированную помощь, заботу и персональный подход!',
    'all_rights_reserved': 'Все права защищены',
    'about_subtitle': 'Узнайте больше о моем опыте, квалификации и подходе к урологической и андрологической помощи',
    'doctor_description_1': 'Имея более 15 лет опыта в урологии и андрологии, я посвятил свою карьеру предоставлению исключительной помощи пациентам с урологическими проблемами и проблемами репродуктивного здоровья.',
    'doctor_description_2': 'Мой подход сочетает в себе новейшие методы лечения, основанные на доказательной медицине, с сострадательной, ориентированной на пациента философией. Я верю в лечение всего человека, а не только заболевания.',
    'doctor_description_3': 'На протяжении всей моей карьеры я остаюсь приверженным постоянному обучению и нахождению на переднем крае достижений в урологической медицине, чтобы предоставить моим пациентам наилучшую возможную помощь.',
    'compassionate_care': 'Заботливый подход',
    'award_winning': 'Признанный специалист',
    'education': 'Образование',
    'certifications': 'Сертификаты',
    'patient_reviews': 'отзывов пациентов',
    'doctor_of_medicine': 'Доктор медицины',
    'residency_in_urology': 'Ординатура по урологии',
    'fellowship_in_andrology': 'Стажировка по андрологии',
    'kyiv_medical_university': 'Киевский медицинский университет',
    'national_medical_academy': 'Национальная медицинская академия последипломного образования',
    'european_association': 'Европейская ассоциация урологии',
    'urologist': 'Уролог',
    'senior_urologist': 'Старший уролог',
    'head_of_urology': 'Заведующий урологическим отделением',
    'kyiv_city_clinical_hospital': 'Киевская городская клиническая больница',
    'medical_center_health': 'Медицинский центр "Здоровье"',
    'medcare_clinic': 'Клиника "МедКеа"',
    'european_board': 'Сертификация Европейского совета урологии',
    'advanced_training': 'Продвинутая подготовка по мужскому репродуктивному здоровью',
    'laser_surgery': 'Сертификация по лазерной хирургии в урологии',
    'minimally_invasive': 'Минимально инвазивные хирургические техники',
    'my_approach': 'Мой подход',
    'patient_centered': 'Ориентированность на пациента',
    'patient_centered_desc': 'Я считаю важным относиться к каждому пациенту как к личности, уделяя время пониманию их конкретных проблем и разработке индивидуальных планов лечения.',
    'evidence_based': 'Доказательная медицина',
    'evidence_based_desc': 'Мои методы лечения основаны на последних научных исследованиях и клинических рекомендациях для обеспечения высочайшего стандарта медицинской помощи.',
    'continuous_education': 'Непрерывное образование',
    'continuous_education_desc': 'Я регулярно участвую в медицинских конференциях и семинарах, чтобы быть в курсе последних достижений в урологии и андрологии.'
  }
};

// Provider component
export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Initialize language from localStorage or default to 'uk'
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage') as Language;
    return savedLanguage && ['uk', 'en', 'ru'].includes(savedLanguage) ? savedLanguage : 'uk';
  });

  // Store language preference in localStorage when it changes
  useEffect(() => {
    localStorage.setItem('preferredLanguage', language);
  }, [language]);

  // Translation function
  const t = (key: unknown): string => {
    if (typeof key !== 'string') {
      console.warn('Translation request with non-string key:', key);
      return '';
    }
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook for using the language context
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
